spring:
  application:
    name: notification-service
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:41025}
    properties:
      "[email.smtp.auth]": false
      "[email.smtp.starttls.enable]": false
      "[email.smtp.connectiontimeout]": 5000
      "[email.smtp.timeout]": 5000
      "[email.smtp.writetimeout]": 5000
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
          multiplier: 2
  redis:
    host: redis
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}